---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos7
    image: centos:7
    pre_build_image: true
    privileged: true
  - name: centos8
    image: centos:latest
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
